# Generated by Django 3.1.2 on 2020-11-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Recipe',
        ),
    ]
